inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

RSpec/ExampleLength:
  Exclude:
    - spec/controllers/api/todo_lists_controller_spec.rb

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
